class ClientesElements < SitePrism::Page
    set_url '/customers'
    element :btn_novo_cliente, 'button[id=dataview-insert-button]'
    element :inp_pesquisar, 'input[id=dataview-search-input]'
    element :btn_pesquisar, 'button[id=dataview-search-button]'
    element :validar_dados, 'tr[id=dataview-table-items-row]'
    element :inp_name, 'input[name=name]'
    element :inp_telefone, 'input[name=phone]'
    element :inp_email, 'input[name=email]'
    element :inp_sexo_m, 'input[name=radio-m]'
    element :inp_sexo_f, 'input[name=radio-f]'
    element :slct_tipo_cliente, 'select[id=type-customer]'
    element :observacoes, 'textarea[name=note]'
    element :btn_salvar, 'button[id=form-submit-button]'
    element :btn_cancelar, 'a[id=form-cancel-button]'
    element :btn_editar_cliente, 'span[id=edit-button]'
    element :btn_deletar_cliente, 'span[id=delete-button]'
    element :titulo_modal, 'h4[class=modal-title]'
    element :btn_confirmar_excluir, 'button[class="btn btn-danger"]'
    element :validar_cliente_excluido, 'div[class="alert alert-warning"]'
end